### DISCUSSION TITLE
Support of Docker Compose workflows

### DISCUSSION THREAD

**Discussion by elprans** [geldata/gel#2897] [Ideas]
Currently, most of `edgedb` dev workflow automation and configuration focuses on setups where the app and its services run directly on the host.  While running on the way to achieve the best balance of ergonomics, security, and performance, we must also consider development setups where the app's components and services are containerized and driven by `docker-compose` or a similar tool.

The primary trade-off required to reduce the friction of running EdgeDB via `docker-compose.yml` is _security_.  

In the standard host-based `edgedb instance` setup we default to strong security which includes using both the password authentication and TLS server authentication for network connections between clients and server instances even when servers are running locally.  Equivalent defaults for `docker-compose` workflows would require either: 

a) users to perform the certificate and password generation steps manually and specify them in `docker-compose.yml`; or 
b) changes to EdgeDB tooling to generate and recognize credentials files in project directories.

Neither option is fully secure, because both require proper secret safeguarding which is always hard when secrets are stored under the project directory because of the risk of accidental commit.  Option b) also introduces race conditions where clients in sibling containers attempt to connect before the credentials were generated.

`docker-compose` is primarily used in development where all components usually run in an isolated network and ports are published on the loopback interface, so network communication security is less of a concern.  Thus, a potential solution to improving the DX of EdgeDB in `docker-compose` is to introduce a special environment variable (let's call it `EDGEDB_INSECURE_DEVMODE`) which would trigger these behaviors:

1. The server client authentication will default to `Trust` (i.e. no password).
2. Clients will automatically trust the auto-generated server TLS certificate.
3. Server will run with `--allow-insecure-http-clients` by default (which is also the mode for local `edgedb instance`-created instances and is needed to make local HTTP development work without major hassle.

The recommended practice would be to place `EDGEDB_INSECURE_DEVMODE` in a `.gitignore`-d `docker-compose.override.yml` to support scenarios where the main `docker-compose.yml` is used in different environments.

### Example 

**`docker-compose.yml`**:

```yaml
services:
  edgedb:
    image: edgedb/edgedb:1-beta3
  app:
    build:
      context: .
    links: [edgedb]
```

**`docker-compose.override.yml`** (development):

```yaml
services:
  edgedb:
    environment:
       EDGEDB_INSECURE_DEVMODE: 1
  app:
    environment:
       EDGEDB_INSECURE_DEVMODE: 1
```

**`docker-compose.override.yml`** (production):

```yaml
services:
  edgedb:
    # pass authentication configuration via env vars
    # or mounted files.
  app:
    # ditto
```

### Using `edgedb` CLI from the host

The `edgedb` CLI contains lots of functionality that is essential to good DX with EdgeDB regardless of how the server is being managed, most importantly the `migration` tools.  Thus, it is expected that users would want to run `edgedb` commands from the host.  This case is supported by `edgedb instance link` and, possibly, `edgedb project init`.  For convenience we should probably let `edgedb instance link` detect the presence of `docker-compose.yml` and ask/infer connection parameters from that.

**Comment by tailhook** [comment]
> The recommended practice would be to place EDGEDB_INSECURE_DEVMODE in a .gitignore-d docker-compose.override.yml to support scenarios where the main docker-compose.yml is used in different environments.

I think it should be placed in non-git-ignored `docker-compose.override.yml`. The Idea is that when you run `docker-compose up` the file is used. But when you run `docker-compose -f docker-comopose.yml -f docker-compose.prod.yml up` the file is ignored. At least this is what [documentation](https://docs.docker.com/compose/extends/) suggests.

Otherwise setting up a project has an extra step. And after you run that extra step, you still have the same issue if it happens that you need to deploy from your laptop.

**Comment by tailhook** [comment]
And `EDGEDB_INSECURE_DEVMODE` should probably be spelled as `EDGEDB_INSECURE_DEV_MODE` (i.e. skipping arbitrary word separators is weird).

**Comment by tailhook** [comment]
Is `EDGEDB_INSECURE_DEV_MODE=1 edgedb instance link` equivalent to `--trust-tls-cert`? Or do we ignore dev-mode flag in `instance link`? Or do we skip `tls_ca_cert` in the generated credentials file so that these credentials only work when `EDGEDB_INSECURE_DEV_MODE=1` is in the environment?

**Comment by tailhook** [comment]
Also docker-compose example should contain `EDGEDB_HOST`:
```
services:
  edgedb:
    image: edgedb/edgedb:1-beta3
  app:
    build:
      context: .
    links: [edgedb]
    environment:
      EDGEDB_HOST: edgedb
```
