### DISCUSSION TITLE
Can't use the UI when developing locally using docker

### DISCUSSION THREAD

**Discussion by dwatson15** [geldata/gel#7207] [Q&A]
Hi, I have the following docker-compose file:

```
services:
  edgedb:
      container_name: edgedb
      ports:
        - 5656:5656
      image: edgedb/edgedb:latest
      environment:
        EDGEDB_SERVER_SECURITY: insecure_dev_mode
        EDGEDB_SERVER_ADMIN_UI: enabled
        EDGEDB_SERVER_BIND_ADDRESS: "0.0.0.0"

      volumes:
        - dbdata:/var/lib/edgedb/data
      restart: unless-stopped
      networks:
        - internal
    
volumes:
  dbdata:

networks:
  internal:
    driver: bridge
```

When spinning this up, I can access https://localhost:5656/ui/_login but I have had no success logging in and using environment variables like `EDGEDB_SERVER_PASSWORD` don't seem to be respected. I also get the following error when trying to log in, presumably because the log in details are incorrect.

```
edgedb  | ---- Exception occurred: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1006) ----
edgedb  | 
edgedb  | 1. ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1006)
edgedb  | 
edgedb  | ---- Traceback ----
edgedb  | 
edgedb  |     edb/server/protocol/protocol.pyx, line 395, in _start_tls
edgedb  |         
edgedb  |     uvloop/loop.pyx, line 1638, in start_tls
edgedb  |         
edgedb  |     uvloop/loop.pyx, line 1631, in uvloop.loop.Loop.start_tls
edgedb  |         
edgedb  |     uvloop/sslproto.pyx, line 517, in uvloop.loop.SSLProtocol._on_handshake_complete
edgedb  |         
edgedb  |     uvloop/sslproto.pyx, line 499, in uvloop.loop.SSLProtocol._do_handshake
edgedb  |         
edgedb  |     /usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/ssl.py, line 979, in do_handshake
edgedb  |         > self._sslobj.do_handshake()
edgedb  | 
edgedb  | ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1006)
edgedb  | ERROR 1 2024-04-16T17:12:43.008 asyncio: Task exception was never retrieved
edgedb  | future: <Task finished name='Task-71' coro=<<coroutine without __name__>()> exception=SSLError(1, '[SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1006)')>

```
 Am I missing something crucial here? I was under the impression that auth wouldn't be needed given I'm using `EDGEDB_SERVER_SECURITY: insecure_dev_mode`
